name: Build Test and Publish Artifacts

on:
  push:
    branches:
    - main

env:
  DOTNET_VERSION: "7.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          cd src/TournamentBackend
          dotnet restore 
          dotnet build --configuration Release --no-restore

      #- name: Test
      #  run: dotnet test --configuration Release --no-build

      - name: Publish Linux
        run: |
          cd src/TournamentBackend
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/linux-x64 -p:PublishSingleFile=true -r linux-x64 --self-contained true



      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: tournament-party.linux-x64.tar
          path: ${{env.DOTNET_ROOT}}
