name: Build & Test Artifact

on:
  push:
    branches:
    - main

env:
  DOTNET_VERSION: "7.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          cd src/TournamentBackend
          dotnet restore WebApi
          dotnet build WebApi --configuration Release --no-restore

      #- name: Test
      #  run: dotnet test WebApi --configuration Release --no-build

      - name: Publish
        run: |
          cd src/TournamentBackend
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: tournament-party
          path: ${{env.DOTNET_ROOT}}/myapp
